### ISSUE TITLE
Cannot Select Any Icon

### ISSUE THREAD

**Issue by jfn4epff6x** [webosbrew/youtube-webos#110]
Cannot select any icon in the youtube video playback area ( channel icon, CC, Comments etc ), please press on the icon it pause or play the video instead

**Comment by futuretrunxy** [comment]
Same problem. Any solution?

**Comment by broXXeln** [comment]
Hello,

I also have the same issue as OP since around last week.


**Current Behavior:**

Not beeing able to select any of the icons (i.e. dis/-enable subtitles, select other videos etc.). Clicking the button "OK" on the Magic Remote only pauses and continues the video.


**Expected Behavior:**

As before last week: On clicking the icons the desired interaction was performed (i.e. subtitles could be disabled/enabled)


**Environment:**

- Device: LG TV
- Model: OLED55CS9LA
- WebOS: 7.3.0-2403
- Version: 0.3.1
- Version(InApp): web_20231210_10_RC01


**Anything else:**

Tried restarting TV, restarting app, changing mouse cursor size in TV settings -> The issue still persists


**What I didn't try (yet):** 

- Changing batteries on magic remote
- Reinstalling app

**Comment by xxxMentoLxxx** [comment]
Hi,
Same here, since last homebrew install.
IS there any solution?

**Comment by AtlasRedux** [comment]
Only pointer don't work (which of course is a major hassle).
You can still use manual controls with up/down/left/right/OK/Enter/Line etc.

**Comment by futuretrunxy** [comment]
The problem solved itself for me yesterday,
I didn't do anything, it works now.

**Comment by xxxMentoLxxx** [comment]
Yes, it works now. Interesting...
