### ISSUE TITLE
Screen Off feature disabled when Youtube app is opened

### ISSUE THREAD

**Issue by hjkvgg59-dev** [webosbrew/youtube-webos#123]
Every app in my LG TV allows me to use the Screen Off feature except for YouTube. I think because WebOS does this for purpose for only the YouTube app. I think this can be solved by building the app with a different signiture.

**Comment by throwaway96** [comment]
You mean a different app ID? I'm not sure that's desirable, since it will break other things (like launching via DIAL).

You can build the app yourself with a different ID. Cloning the repo, changing all instances of `youtube.leanback.v4` to whatever you want, enabling actions, and creating a release should work.

If your TV is rooted, you could also investigate disabling this functionality some other way.
