### ISSUE TITLE
Outdated dependencies and broken build config

### ISSUE THREAD

**Issue by fire332** [webosbrew/youtube-webos#16]
![image](https://user-images.githubusercontent.com/96039230/148518178-b2d79766-e8c9-4f1a-b609-b774cf5b3960.png)

Dependencies are severely out of date. **I've manually checked through the newer major versions of each dep and they can be upgraded without any further change as they don't break anything we care about.** With the dependencies out of date, these errors occur:
![image](https://user-images.githubusercontent.com/96039230/148525521-d83ef059-d995-4188-be19-7ff04d0fff05.png)

Additionally, `@webosose/ares-cli` is only intended for use with the open source version of webos and not LG TV's version since it's missing ares-novacom, as [the employee on the LG developer forums can attest to that](https://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC17165606&sMenuId=53&contsTypeCode=QUE&prodTypeCode=TV#none). Additionally, `@webosose/ares-cli` causes npm to spew a lot of audit errors when installing so **I recommend removing this package as this can cause real audit problems to be missed.**

For the webpack config, using `es5` for targets will cause this error:
![image](https://user-images.githubusercontent.com/96039230/148526638-f31e022e-6850-4f6d-9e54-97cfc72d87b1.png)
**I recommend moving the target in `babel.config.json` to a separate browserslist file and set `target: 'browserslist'` in webpack's config instead.**

**Comment by Informatic** [comment]
Hey, thanks for checking in.

1. I think we may have a very different definitions of "severely out of date" - it's just ~6 months old.
In that period NodeJS 17 was released, which introduced some breaking changes (which IMO should've been announced/put behind a warning first :/) - this project was released when 16 was the current version, and it's still technically active. Anyways - webpack update makes sense here to keep it compatible.

2. Packaging tooling in webosose/ares-cli is essentially the same as for webOS TV SDK. If we couldn't use webosose/ares-cli (be it for the licensing, or it just not existing in the first place) I would genuinely consider building our own packaging tooling, since I am not really willing to pull in the full webOS TV SDK into CI just for these tiny tools. This has been tested fairly well in pretty much all webosbrew-adjacent projects and we never noticed any issues with these. `ares-novacom` is essentially the only tool that is missing, and we are considering reimplementing that in our own fork of/extension to `@webosose/ares-cli` in near future.
As for npm audit - I think it should be possible to update transitive dependencies of our dependencies to properly silence npm audit tool. `npm audit` will not complain about old unmaintained dependencies of webOS TV SDK tooling since it's not aware of them existing in the first place. That's probably one of the arguments **for** using npm-packaged tooling. :smile: 

3. This is likely caused by webpack update from the first point.

Feel free to file a PR for points 1 and 3.

**Comment by Informatic** [comment]
2. Looking at `@webosose/ares-cli` now it seems like `tar` update will not be trivial due to their migration to ES6 - we'll fork and fix that then.

**Comment by fire332** [comment]
Do you know how to get `@webosose/ares-cli`'s ares-install to work on windows? It keeps saying it can't find the ipk file no matter what I do to the path. Also another reason why I use the closed source ares-cli.

**Comment by Informatic** [comment]
Can you share the actual error you get, so that I could follow the codepath that is followed? webOS OSE project [claims](https://www.webosose.org/docs/tools/sdk/cli/cli-user-guide/#operating-systems) to support Windows, but they also explicitly state node.js 8 - 14. This may be another issue caused by too new nodejs version. (webOS TV SDK ships its own outdated nodejs)

Anwyays, another argument for forking it off and patching up.

**Comment by fire332** [comment]
... I can't even get to that part now as I'm now getting this......

![image](https://user-images.githubusercontent.com/96039230/148542160-b02705da-ae0c-47d0-8072-280f3a1e18e0.png)

**Comment by Informatic** [comment]
1. Please, don't ever use `npx`, you are going to have a bad time. Use `node_modules/.bin/ares-install` after dependencies have been installed.
2. `ares-setup-device` in that case is webOS TV SDK tool - these use a different configuration file. (another reason for not using official SDK since it pollutes a global path, and we have no control over SDK version someone uses - making it impossible to have reproducible development environment) Use `node_modules/.bin/ares-setup-device`.

**Comment by fire332** [comment]
The deploy script doesn't work in Windows because powershell and cmd doesn't support `${}` string substitution. Probably should write a deploy script.
![image](https://user-images.githubusercontent.com/96039230/148546290-66c0a83e-eeb3-4e5b-a927-b7a7dcd199f1.png)

**Comment by Informatic** [comment]
Ah, that explains it now. Too bad npm doesn't try to resolve these... :/

**Comment by fire332** [comment]
After not using npx, ares-install doesn't have any trouble finding the IPK file anymore. Seems like `npx` and `@webosose/ares-cli` doesn't go well together.

**Comment by fire332** [comment]
Do you mind if I throw in my prettier, eslint, and vscode configs while I'm at it? I'm kinda tired of having to stash them every time I want to do anything involving git.

**Comment by Informatic** [comment]
Sure, no problem.
