### ISSUE TITLE
Bug: Red warning banner overlay

### ISSUE THREAD

**Issue by sunnyd24** [webosbrew/youtube-webos#177]
- YTAF version: 0.3.4
  - firmware version: 05.30.45
  - webOS version: 4.9.0
  - OTAID: HE_DTV_W19O_AFABABAA
  - SoC: o18
  - Model: OLED65W9PLA

## Issue description
Continuous error message overlay banner in red shown in bottom left corner of TV screen, as below when sending/casting any video from official YouTube mobile app to LG TV. 

Error message displayed :
`WARNING: REMOVE DEBUG QUERY PARAMETERS [env_forceFullAnimation=1 theme=k dialLaunch=watch reversePairingCode=REDACTED BEFORE PRODUCTION RELEASE. MDx screen id: REDACTED`

Photo or error displayed:
![20240509_170505](https://github.com/webosbrew/youtube-webos/assets/46629122/d6677506-ba2d-45dc-8e4d-7773c9053953)

**Comment by throwaway96** [comment]
Oh, that is interesting. I wonder which one it's upset about... probably `env_forceFullAnimation=1`. I will have to see if that can be removed without breaking things.

And thank you for providing the requested information.

**Comment by cremor** [comment]
> probably `env_forceFullAnimation=1`. I will have to see if that can be removed without breaking things.

I remember that I've seen a commit - I think from you - where some JavaScript code was removed with a commit message mentioning that it isn't needed because of `env_forceFullAnimation=1`. Sadly I can't find that commit any more now. But I think it contained the code from https://github.com/reisxd/TizenTube/commit/185f4580c3f3552342cc9c840cf5f2f531cdb723#diff-2088c7b7e9291a3dabb412ac73269bda591c7cc6c6aa5ec1cd76179d44537ee8
I guess that code would then be needed again.

**Comment by throwaway96** [comment]
Try this build: <https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.5-dev1>

**Comment by sunnyd24** [comment]
> Try this build: https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.5-dev1

OK testing this now, will let you now how I get on.

**Comment by sunnyd24** [comment]
All working now with no red banner. 

Update resolved issue with thanks.
