### ISSUE TITLE
Can't build the code. Missing ares.js file.

### ISSUE THREAD

**Issue by 321Kami** [webosbrew/youtube-webos#28]
Hi,
Can you help me with fixing following error?
morpheus@NUC:~/youtube-webos$ npm install
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/morpheus/youtube-webos/node_modules/@webosose/ares-cli/bin/ares.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/morpheus/youtube-webos/node_modules/@webosose/ares-cli/bin/ares.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

Thanks
KB

**Comment by Informatic** [comment]
That file is supposed to be there, sounds like some corrupted install - try removing `node_modules` directory altogether and run `npm install` again. Check if you have enough storage to install all the dependencies. (~190MB)

**Comment by 321Kami** [comment]
What's interesting I don't have this folder at all - this is fresh checkout:
![image](https://user-images.githubusercontent.com/98164750/150534343-2bf38a71-defe-4882-8643-a7480ab80021.png)

**Comment by Informatic** [comment]
That is really odd. It is supposed to first download all the packages (into
node_modules directory next to package.json file you see) and only then
fixup any permissions. Which node / npm version do you have?

**Comment by 321Kami** [comment]
This is just standard Ubuntu installation:
![image](https://user-images.githubusercontent.com/98164750/150535035-e8d821ec-0ca6-43fd-a70b-367f68e11239.png)

**Comment by 321Kami** [comment]
Adding log
[2022-01-21T13_39_27_081Z-debug.log](https://github.com/webosbrew/youtube-webos/files/7914084/2022-01-21T13_39_27_081Z-debug.log)
s

**Comment by Informatic** [comment]
I would try wiping (or temporarily moving) npm cache in `~/.npm` directory. This still looks like some unexplained filesystem corruption to me... :/

**Comment by 321Kami** [comment]
Update - it works just fine when I switch to "root" account... why does it require root privileges to perform "install" command?

**Comment by Informatic** [comment]
I have absolutely no idea, sorry. There is no reason for that.

Our CI works as non-root (iiuc, it's GitHub Actions...), I have never used `npm` as root on any of my machines either, nor have every stumbled upon a similar issue anywhere in the past 4+ years of using `npm` fairly regularly, outside of situations where some permissions were obviously broken (eg. `/home/$USER/.npm/*` could be owned by `root` because someone has ran `sudo -E npm ...`-like command that would keep `$HOME` environment in place)

I am guessing Your home directory is not on some exotic filesystem like NTFS or exFAT - is that correct?

**Comment by 321Kami** [comment]
Ok I fixed the issue. What I did I just removed the whole directory once again, ran npm update without root and then checked out repository and executed npm install. Issue to be closed.
Btw. are you Polish and maybe located somewhere close to Gdansk? I saw some history regarding searching for "przekop mierzei wislanej" :)

**Comment by NeoNavras** [comment]
Throwing my experience in: I had the same issue/error 
```npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/myuser/Projects/WebOS/brew-youtube-webos/node_modules/@webosose/ares-cli/bin/ares.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/myuser/Projects/WebOS/brew-youtube-webos/node_modules/@webosose/ares-cli/bin/ares.js'
npm ERR! enoent This is related to npm not being able to find a file.
```

when I first tried to run `npm install` and thus also couldn' build - getting this error when I tried to build:
```npm ERR! code 1
npm ERR! path /home/camlis/Projects/WebOS/brew-youtube-webos
npm ERR! command failed
npm ERR! command sh -c webpack
```

Which is funny because I could run `npm install` in the source fork (of FriedChickenButt) no problem and then also build it. `sudo npm install` same thing. I tried to `ln -s` my SDK install where the _ares*_ things are located to the mentioned path, but the error persisted. `sudo apt install webpack` also didn't make it better. `npm install copy-webpack-plugin --save-dev` with first error. 

What worked for me somehow is deleting the file `package-lock.json` then I could `npm install` and build. App also seems to be working as expected on the TV. Or did deleting the file and building without it has consequences for the app? Now when I pull the repo again with the original `package-lock.json` I can't reproduce the errors I got. I have no idea whats going on.

**Comment by NeoNavras** [comment]
Well I just did `npm update` and now the build is not working again. I'm getting the error 
```
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/myuser/Projects/WebOS/brew-youtube-webos/node_modules/@webosose/ares-cli/bin/ares-package.js'
  ]
}
npm ERR! code 1
npm ERR! path /home/myuser/Projects/WebOS/brew-youtube-webos
npm ERR! command failed
npm ERR! command sh -c ares-package -n dist

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2022-02-04T15_27_24_186Z-debug.log
```
But at least `npm install` is working better now, as it is not throwing "found x vulnerablities" at me anymore. Help.

**Comment by Informatic** [comment]
Plain `npm install` should be sufficient and works well for me. (NodeJS v14.18.3, NPM 6.14.15)

It works in our CI (which does a clean checkout + clean `npm install` on NodeJS 14) - which NPM/NodeJS version are you on?

**Comment by NeoNavras** [comment]
`npm --version`: 7.5.2
`nodejs --version`: v12.21.0
Up to date default repository installs (PopOS) as far as I can tell.

**Comment by NeoNavras** [comment]
Alright I installed NVM from https://github.com/nvm-sh/nvm and installed your NodeJS version with `nvm install v14.18.3` which also installed your NPM version. Now I can npm install, build and package the project. But is it normal/expected that the npm install says to me "found 16 vulnerabilities (8 moderate, 8 high)"? Should I run `npm update`?

**Comment by Informatic** [comment]
No, these don't really matter in that case (these are bugs in transient dependencies of `@webosose/ares-cli` tool which is only used in build/package time) and `npm update` would probably not fix it anyways. (since it just updates local dependencies, not transient, ie. dependencies of our dependencies...)

I have an initial forked off `ares-cli` that bumps these dependencies but we haven't pulled that in anywhere yet.
