### ISSUE TITLE
Does not save YouTube browsing history

### ISSUE THREAD

**Issue by strdik** [webosbrew/youtube-webos#31]
Hello, version 0.3.0 does not save the video browsing history, if you exit and do not finish watching, then after logging in, the video starts from the beginning, is it possible to use some command to make the video save the browsing history of webos 3.9

**Comment by Informatic** [comment]
This has seemingly been fixed in #24 which will be released in an updated version this weekend probably.
You can check test builds here: https://github.com/webosbrew/youtube-webos/pull/24#issuecomment-1013831027

**Comment by strdik** [comment]
That is, as I correctly understood, there will be a new update this weekend and you will fix this problem with the viewing history and the video will be saved on webos 3.9

**Comment by Informatic** [comment]
Check v0.3.1 up on Homebrew Channel.

**Comment by strdik** [comment]
Thank you, I've updated it now, I've watched the video while it saves, well, I'll watch other videos and unsubscribe, and what was the reason in the viewing history. What was the mistake?

**Comment by strdik** [comment]
> Проверьте v0.3.1 на канале Homebrew.

Thank you for fixing the YouTube problem, but you didn't write what the problem was or it's a mystery, I just would like to know for the future. Thanks again!!!

**Comment by Informatic** [comment]
We had some very old adblocking code that relied on blocking HTTP requests/domains. That did not block ads since YouTube changed the way they serve ads (we used "new" adblocking method since first public release, and that code was leftovers from initial test of the original author), but this *was* interfering with some of their analytics requests - seems like if any analytics requests fail during playback YouTube TV no longer reports playback progress.

**Comment by Informatic** [comment]
Closing this now since it should be fixed already.
