### ISSUE TITLE
SponsorBlock segments not rendered on videos with chapters

### ISSUE THREAD

**Issue by Informatic** [webosbrew/youtube-webos#8]
Seems like chapters have just been rolled out to YouTube TV. This causes our SponsorBlock segments rendering to break.

Skips are properly executed.

Test video: https://www.youtube.com/watch?v=R3iNAQqqnjE
![Screen capture](https://user-images.githubusercontent.com/1131102/147372798-de835b64-53f5-41ac-99e3-c2963507f1aa.png)

**Comment by Informatic** [comment]
New slider class: `.ytlr-multi-markers-player-bar-renderer`
![slider](https://user-images.githubusercontent.com/1131102/147372848-f219f0f9-5afc-405b-a74e-d226cf80b030.png)

**Comment by Informatic** [comment]
Another issue: original slider is replaced with segmented one fairly randomly - we now also need to watch for slider removal in parent node. Whoops.

**Comment by LuminescentMoon** [comment]
Just an update on this: I've made a quick preact component a while back that emulates the rect and opacity/visibility of a unmanaged element in a managed element which would allow having the sponsorblock overlay "in" the slider while being out of YT's VDOM. The only reason I haven't made a pull request with it is because I had trouble emulating the proper stacking context which means the sponsorblock overlay would not be behind certain elements as it should be, causing minor visual bugs.

Just ping me if you want the code for it as I'm busy with other stuff.

**Comment by fire332** [comment]
Fixed by #103.
